micronaut:
  application:
    name: learnAuth
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/crudTest?currentSchema=jwt_auth
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: johnny
    password: mysecretpassword
